Repository AsliSema/byte-and-bite, pull requests merged in 2023-08, with the labels that each got.

#93 Add tests for dish controllers
  src/controllers/__tests__/dish.test.ts
Labels: enhancement

#95 optional address related updates
  src/models/dish.ts
  src/models/user.ts
  src/types/express.ts
Labels: bug, enhancement

#97 removed ratingsAverage and ratingsQuantity
  src/utils/validators/dishValidator.ts
Labels: bug, enhancement

#98 added Google Signin
  package.json
  src/app.ts
  src/config/config.ts
  src/config/passport.ts
  src/routes/googleAuth.ts
  src/routes/pages.ts
  src/views/home.ejs
  src/views/login.ejs
  tsconfig.json
Labels: enhancement

#101 Fix bugs
  src/controllers/auth.ts
  src/controllers/cart.ts
  src/models/dish.ts
  src/routes/admin.ts
  src/routes/auth.ts
  src/routes/cart.ts
  src/utils/validators/authValidator.ts
  src/utils/validators/dishValidator.ts
Labels: bug

#102 cart routes testing and init test
  package.json
  src/app.ts
  src/config/config.ts
  src/db/connection.ts
  src/routes/__tests__/cart.test.ts
Labels: enhancement

#104 Dish route test
  src/controllers/__tests__/auth.test.ts
  src/controllers/__tests__/cart.test.ts
  src/controllers/__tests__/contactUs.test.ts
  src/controllers/__tests__/dish.test.ts
  src/controllers/__tests__/order.test.ts
  src/controllers/dish.ts
  src/routes/__tests__/dish.test.ts
Labels: enhancement

#106 update cart route tests to clear everything after
  src/routes/__tests__/cart.test.ts
Labels: enhancement

#107 update auth test routes
  src/routes/__tests__/auth.test.ts
Labels: enhancement

#109 added Should
  src/routes/__tests__/cart.test.ts
Labels: enhancement

#110 update order tests and package.json test
  package.json
  src/routes/__tests__/order.test.ts
Labels: enhancement

#112 Update GET /order route
  src/routes/admin.ts
Labels: bug

#113 Update test records
  package.json
  src/routes/__tests__/admin.test.ts
  src/routes/__tests__/auth.test.ts
  src/routes/__tests__/cart.test.ts
  src/routes/__tests__/order.test.ts
Labels: bug

#114 Add figma files to homepage
  src/views/home.ejs
Labels: documentation

#121 updated api docs and google links
  src/db/connection.ts
  src/routes/googleAuth.ts
  src/views/home.ejs
Labels: bug, enhancement
