Repository AsliSema/byte-and-bite, pull requests merged in 2023-07, with the labels that each got.

#12 Typescript configuration
  .gitignore
  package-lock.json
  package.json
  src/app.ts
  src/controllers/auth.ts
  src/controllers/card.ts
  src/controllers/dish.ts
  src/controllers/order.ts
  src/models/card.ts
  src/models/dish.ts
  src/models/order.ts
  src/models/review.ts
  src/models/user.ts
  src/routes/auth.ts
  src/routes/card.ts
  src/routes/dish.ts
  src/routes/order.ts
  tsconfig.json
  yarn.lock
Labels: documentation

#46 Add| validator middleware and add it to routes.
  src/middlewares/validatorMiddleware.ts
  src/routes/auth.ts
  src/routes/dish.ts
  src/utils/validators/authValidator.ts
  src/utils/validators/dishValidator.ts
Labels: enhancement

#50 update cart controller
  src/controllers/cart.ts
  src/models/cart.ts
Labels: bug

#51 delete dish inside cart
  src/controllers/cart.ts
  src/routes/cart.ts
Labels: enhancement

#52 update user for admin routes
  src/app.ts
  src/controllers/admin.ts
  src/routes/admin.ts
Labels: enhancement

#55 ADD rest of cart routes
  src/controllers/cart.ts
  src/routes/cart.ts
Labels: enhancement

#61 Update user profile
  src/controllers/admin.ts
  src/controllers/auth.ts
  src/routes/admin.ts
  src/routes/auth.ts
Labels: enhancement

#71 fix components part
  src/utils/swagger.ts
Labels: bug

#75 ADD review & order swagger
  src/controllers/dish.ts
  src/models/dish.ts
  src/models/order.ts
  src/routes/dish.ts
  src/routes/order.ts
  src/utils/validators/dishValidator.ts
Labels: documentation

#78 done swagger task 2
  src/routes/admin.ts
  src/routes/auth.ts
Labels: documentation

#77 Finished Swagger task 4
  src/controllers/dish.ts
  src/routes/cart.ts
  src/routes/dish.ts
  src/routes/order.ts
Labels: documentation

#79 add some routes for admin
  src/controllers/auth.ts
  src/models/user.ts
  src/routes/admin.ts
Labels: enhancement

#80 ADD contact us route + new order email
  package.json
  src/app.ts
  src/controllers/contactUs.ts
  src/controllers/order.ts
  src/routes/contactUs.ts
  src/utils/sendEmail.ts
  src/utils/validators/contactValidator.ts
Labels: enhancement
